services:
    imkingdavid.spoiler.listener:
        class: imkingdavid\spoiler\event\listener
        arguments:
            - @config
            - @controller.helper
            - @template
            - @user
            - %core.php_ext%
        tags:
            - { name: event.listener }
